# ============================================================
# File: scripts/process_data.py
# ============================================================

"""
Builds the searchable FAQ artifact set.

This script performs the offline data-processing step for the Smart FAQ Search App:
1. Loads raw FAQ records from CSV.
2. Normalizes question and answer text.
3. Builds a TF-IDF search index.
4. Saves the processed data and trained retrieval artifacts.
"""

from pathlib import Path

import joblib
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer


PROJECT_ROOT = Path(__file__).resolve().parents[1]

RAW_DATA_PATH = PROJECT_ROOT / "data" / "raw" / "faqs.csv"
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"

PROCESSED_DATA_PATH = ARTIFACTS_DIR / "processed_faqs.csv"
VECTORIZER_PATH = ARTIFACTS_DIR / "tfidf_vectorizer.joblib"
MATRIX_PATH = ARTIFACTS_DIR / "tfidf_matrix.joblib"


def clean_text(text: object) -> str:
    """
    Normalize text for consistent indexing and retrieval.

    The cleaning is intentionally lightweight because TF-IDF benefits from
    preserving the original terms while removing casing and spacing noise.
    """
    return " ".join(str(text).lower().strip().split())


def run_pipeline() -> None:
    """
    Execute the full preprocessing pipeline and persist all search artifacts.
    """
    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(RAW_DATA_PATH)

    required_columns = {"id", "question", "answer", "category"}
    missing_columns = required_columns.difference(df.columns)

    if missing_columns:
        raise ValueError(f"Missing required columns: {sorted(missing_columns)}")

    df["clean_question"] = df["question"].apply(clean_text)
    df["clean_answer"] = df["answer"].apply(clean_text)

    df["search_text"] = df["clean_question"] + " " + df["clean_answer"]

    vectorizer = TfidfVectorizer(stop_words="english")
    tfidf_matrix = vectorizer.fit_transform(df["search_text"])

    df.to_csv(PROCESSED_DATA_PATH, index=False)
    joblib.dump(vectorizer, VECTORIZER_PATH)
    joblib.dump(tfidf_matrix, MATRIX_PATH)

    print("Pipeline completed successfully.")
    print(f"Processed data saved to: {PROCESSED_DATA_PATH}")
    print(f"Vectorizer saved to: {VECTORIZER_PATH}")
    print(f"Matrix saved to: {MATRIX_PATH}")


if __name__ == "__main__":
    run_pipeline()


# ============================================================
# File: app/search_engine.py
# ============================================================

"""
Search engine module for retrieving relevant FAQ answers.

The engine loads the precomputed TF-IDF artifacts generated by
scripts/process_data.py and compares user queries against the FAQ index
using cosine similarity.
"""

from pathlib import Path

import joblib
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity


PROJECT_ROOT = Path(__file__).resolve().parents[1]
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"

PROCESSED_DATA_PATH = ARTIFACTS_DIR / "processed_faqs.csv"
VECTORIZER_PATH = ARTIFACTS_DIR / "tfidf_vectorizer.joblib"
MATRIX_PATH = ARTIFACTS_DIR / "tfidf_matrix.joblib"


class FAQSearchEngine:
    """
    Loads FAQ retrieval artifacts and serves similarity-ranked search results.
    """

    def __init__(self) -> None:
        self.df = pd.read_csv(PROCESSED_DATA_PATH)
        self.vectorizer = joblib.load(VECTORIZER_PATH)
        self.tfidf_matrix = joblib.load(MATRIX_PATH)

    @staticmethod
    def clean_query(query: object) -> str:
        """
        Apply the same lightweight normalization used during indexing.
        """
        return " ".join(str(query).lower().strip().split())

    def search(self, query: str, top_k: int = 3) -> list[dict]:
        """
        Return the top-k FAQ entries ranked by cosine similarity.

        Args:
            query: User search question.
            top_k: Maximum number of FAQ matches to return.

        Returns:
            A list of FAQ result dictionaries with metadata and similarity scores.
        """
        clean_query = self.clean_query(query)

        if not clean_query:
            return []

        query_vector = self.vectorizer.transform([clean_query])
        similarities = cosine_similarity(query_vector, self.tfidf_matrix).flatten()

        ranked_indexes = similarities.argsort()[::-1]
        top_indexes = ranked_indexes[:top_k]

        results = []

        for index in top_indexes:
            row = self.df.iloc[index]

            results.append(
                {
                    "id": int(row["id"]),
                    "question": row["question"],
                    "answer": row["answer"],
                    "category": row["category"],
                    "score": float(similarities[index]),
                }
            )

        return results


# ============================================================
# File: app/api.py
# ============================================================

"""
FastAPI backend for the Smart FAQ Search App.

The API exposes a health endpoint and a search endpoint that returns
ranked FAQ matches from the TF-IDF retrieval engine.
"""

from fastapi import FastAPI, Query

from app.search_engine import FAQSearchEngine


app = FastAPI(title="Smart FAQ Search API")

search_engine = FAQSearchEngine()


@app.get("/health")
def health_check() -> dict:
    """
    Confirm that the API service is available.
    """
    return {"status": "ok"}


@app.get("/search")
def search_faqs(
    query: str = Query(..., min_length=1),
    top_k: int = Query(3, ge=1, le=5),
) -> dict:
    """
    Search the FAQ knowledge base and return the strongest matches.
    """
    results = search_engine.search(query=query, top_k=top_k)

    return {
        "query": query,
        "results": results,
    }


# ============================================================
# File: app/ui.py
# ============================================================

"""
Streamlit interface for the Smart FAQ Search App.

The UI collects a user question, sends it to the FastAPI backend,
and renders the ranked FAQ results with category and similarity score.
"""

import requests
import streamlit as st


API_URL = "http://127.0.0.1:8000/search"


st.set_page_config(
    page_title="Smart FAQ Search",
    layout="centered",
)

st.title("Smart FAQ Search App")
st.write("Ask a question, and the app will find the closest FAQ answer.")

query = st.text_input("Enter your question:")
top_k = st.slider("Number of results", min_value=1, max_value=5, value=3)

search_clicked = st.button("Search")

if search_clicked:
    if not query.strip():
        st.warning("Please enter a question.")
    else:
        params = {
            "query": query,
            "top_k": top_k,
        }

        try:
            response = requests.get(API_URL, params=params, timeout=10)
            response.raise_for_status()

            data = response.json()
            results = data["results"]

            st.subheader("Search Results")

            for result in results:
                st.markdown(f"### {result['question']}")
                st.write(result["answer"])
                st.write(f"Category: `{result['category']}`")
                st.write(f"Similarity score: `{result['score']:.3f}`")
                st.divider()

        except requests.exceptions.RequestException:
            st.error("Could not connect to the API. Make sure FastAPI is running.")
